Add readme
Videomatik/player pull request #9
Opened 2022-11-09 20:39 UTC by renanblamas

2022-11-09 21:14 UTC, nihey requested changes
Ficou muito bom o README.md, só colocaria aquela parte do seletor de CSS ou HTMLElement na instanciação do VideomatikPlayer.

2022-11-09 21:14 UTC, nihey commented on README.md
> +const player = new VideomatikPlayer({
```suggestion
const player = new VideomatikPlayer('<css selector or HTMLElement instance>', {
```

2022-11-10 19:25 UTC, nihey approved these changes

2022-11-12 19:51 UTC, BrOrlandi commented on README.md
> +TODO
Falta criar um exemplo simples e direto pra testar.

2022-11-12 19:52 UTC, BrOrlandi commented on README.md
> +//TODO
Falta criar uma categoria com os possíveis erros API Key invalida, template id inválido, composition inválida.

2022-11-14 19:51 UTC, renanblamas commented on README.md
> +//TODO
https://github.com/Videomatik/player/pull/9/commits/6c85e9106239bfe5d1202a3f6270ee612593abbb

2022-11-14 21:28 UTC, renanblamas commented on README.md
> +TODO
https://github.com/Videomatik/player/pull/9/commits/1c7cdfccb8ee49b096d7841a411f0dfb2233f75f

2022-11-15 13:09 UTC, nihey commented on README.md
> +<div id="videomatik-player"></div>
Só colocaria esse comentário para ficar um código válido dentro do exemplo

```suggestion
// Considering this div exists: <div id="videomatik-player"></div>
```

2022-11-15 13:15 UTC, nihey approved these changes

2022-11-15 13:16 UTC, BrOrlandi commented on README.md
> +<div id="videomatik-player"></div>
Acho que não precisa, já vi Readmes assim, só pra mencionar que existe uma div com o id, não precisa ficar em modo comentário essa linha, o dev vai sacar que não é exatamente assim que roda.

2022-11-15 14:29 UTC, nihey approved these changes

2022-11-15 14:42 UTC, merged